---
name: Build and Push Quasar / Nginx image to Google Cloud Platform
on:
  push:
    branches: [main]
jobs:
  build-push-gcr:
    name: Build and push to GCP
    runs-on: ubuntu-latest
    env:
      REGION_NAME: 'us-east1-docker.pkg.dev'
      PROJECT_ID: 'extended-poetry-223323'
      REGISTRY_NAME: 'web-tenares'
      IMAGE_NAME: 'web-tenares-image'
      SERVICE_ACCOUNT: github-actions@extended-poetry-223323.iam.gserviceaccount.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Build Docker image'
        run: |
          docker buildx build --platform=linux/amd64 -t $REGION_NAME/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME .

      - name: 'Tag Docker image'
        run: |
          docker tag $REGION_NAME/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME \$REGION_NAME/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME

      - name: 'Push Docker image'
        run: |
          docker push https://$REGION_NAME/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME
