---
name: Build and Push Quasar / Nginx image to Google Cloud Platform
on:
  push:
    branches: [main]
jobs:
  build-push-gcr:
    name: Build and push to GCP
    runs-on: ubuntu-latest
    env:
      REGION_NAME: us-east1-docker.pkg.dev
      PROJECT_ID: extended-poetry-223323
      REGISTRY_NAME: web-tenares
      IMAGE_NAME: web-tenares-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 363.0.0'
          project_id: $PROJECT_ID
          service_account_key: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: Build Docker image
        run: |
          docker buildx build --platform=linux/amd64 -t us-east1-docker.pkg.dev/extended-poetry-223323/web-tenares/web-tenares-image .

      - name: Tag Docker image
        run: |
          docker tag us-east1-docker.pkg.dev/extended-poetry-223323/web-tenares/web-tenares-image \
            us-east1-docker.pkg.dev/extended-poetry-223323/web-tenares/web-tenares-image

      - name: Push Docker image
        run: |
          docker push us-east1-docker.pkg.dev/extended-poetry-223323/web-tenares/web-tenares-image
