---
name: Build and Push Quasar / Nginx image to Google Cloud Platform
on:
  push:
    branches: [main]
jobs:
  build-push-gcr:
    name: Build and push to GCP
    runs-on: ubuntu-latest
    env:
      REGION_NAME: us-east1-docker.pkg.dev
      PROJECT_ID: extended-poetry-223323
      REGISTRY_NAME: web-tenares
      IMAGE_NAME: web-tenares-image
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Set up Cloud auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Build Docker Image
        run: docker buildx build --platform=linux/amd64 -t $IMAGE_NAME:latest .

      - name: Configure Docker client
        run: gcloud auth configure-docker --quiet

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: v0.1.0
        run: |-
          docker tag $IMAGE_NAME:latest $REGION_NAME/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME
          docker tag $IMAGE_NAME:latest $REGION_NAME/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME:$GIT_TAG
          docker push $REGION_NAME/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME
          docker push $REGION_NAME/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME:$GIT_TAG
