---
name: Build and Push Vue/Quasar/Nginx image to Google Cloud Platform
on:
  push:
    branches: [main]
jobs:
  build-push-gcr:
    name: Build image and push to GCP
    runs-on: ubuntu-latest
    env:
      REGION_NAME: 'us-east1-docker.pkg.dev'
      PROJECT_ID: 'extended-poetry-223323'
      REGISTRY_NAME: 'web-tenares'
      IMAGE_NAME: 'web-tenares-image'
      GOOGLE_MAPS_API_KEY: '${{ secrets.GOOGLE_MAPS_API_KEY }}'
      FIREBASE_USERNAME: '${{ secrets.FIREBASE_USERNAME }}'
      FIREBASE_PASSWORD: '${{ secrets.FIREBASE_PASSWORD }}'
      HECTOR_BASE_URL: '${{ secrets.HECTOR_BASE_URL }}'
      HECTOR_USERNAME: '${{ secrets.HECTOR_USERNAME }}'
      HECTOR_TYPE: '${{ secrets.HECTOR_TYPE }}'
      FIREBASE_API_KEY: '${{ secrets.FIREBASE_API_KEY }}'
      FIREBASE_AUTH_DOMAIN: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'
      FIREBASE_DATABASE_URL: '${{ secrets.FIREBASE_DATABASE_URL }}'
      FIREBASE_PROJECT_ID: '${{ secrets.FIREBASE_PROJECT_ID }}'
      FIREBASE_STORAGE_BUCKET: '${{ secrets.FIREBASE_ntSTORAGE_BUCKET }}'
      FIREBASE_MESSAGING_SENDER_ID: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'
      FIREBASE_APP_ID: '${{ secrets.FIREBASE_APP_ID }}'
      FIREBASE_MEASUREMENT_ID: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'
    steps:
      - name: 'Export env variables'
        run: |
          export GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY \
            GMAP=$GOOGLE_MAPS_API_KEY
            FIREBASE_USERNAME=$FIREBASE_USERNAME \
            FIREBASE_PASSWORD=$FIREBASE_PASSWORD \
            HECTOR_BASE_URL=$HECTOR_BASE_URL \
            HECTOR_USERNAME=$HECTOR_USERNAME \
            HECTOR_TYPE=$HECTOR_TYPE \
            FIREBASE_API_KEY=$FIREBASE_API_KEY \
            FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN \
            FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL \
            FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID \
            FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET \
            FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID \
            FIREBASE_APP_ID=$FIREBASE_APP_ID \
            FIREBASE_MEASUREMENT_ID=$FIREBASE_MEASUREMENT_ID

      - name: 'PRINT ECHO'
        run: echo $GMAP

      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: 'Authenticate region'
        run: |
          gcloud auth configure-docker $REGION_NAME

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Build Docker image'
        run: docker buildx build --platform=linux/amd64 -t $REGION_NAME/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME .

      - name: Push Docker image
        run: docker push $REGION_NAME/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME
